/**
 * Centralized application configuration: names, timeouts, limits.
 * Rule: if a static value shows up in more than one place, or if it is a "magic
 * number" inside a component, it lives here.
 */
export const appConfig = {
  name: 'AI Form Creator',
  description: 'Create and publish dynamic forms generated by AI.',
  locale: 'en-US',
} as const;

export const httpConfig = {
  /** Timeout of any HTTP request. */
  requestTimeoutMs: 15_000,
  defaultHeaders: {
    accept: 'application/json',
  },
} as const;

export const queryConfigValues = {
  /** How long cached data is considered fresh. */
  staleTimeMs: 60_000,
  retryCount: 0,
} as const;

export const uiConfig = {
  /** How long a toast lasts before closing itself. */
  notificationTimeoutMs: 5_000,
  /** Standard debounce for inputs triggering side effects. */
  inputDebounceMs: 300,
} as const;

/** HTTP codes used in the app. Avoids comparing against magic numbers. */
export const httpStatus = {
  unauthorized: 401,
  forbidden: 403,
  notFound: 404,
  unprocessableEntity: 422,
} as const;
